apiVersion: v1
kind: Service
metadata:
  name: textextractor-svc
#  namespace: estrix-textextractor-namespace
spec:
  selector:
    app: textextractor-svc
  ports:
   -  protocol: TCP
      port: 8004
      targetPort: 8004
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: textextractor-svc
#  namespace: estrix-textextractor-namespace
  labels:
    app: textextractor-svc
    group: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textextractor-svc
  template:
    metadata:
      labels:
        app: textextractor-svc
        type: svc
    spec:
      containers:
        - name: textextractor-svc
          image: kamilmucik/textextractor:0.0.1
          ports:
            - containerPort: 8004
